# Generated by Django 2.1.5 on 2019-01-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='goods_method',
        ),
        migrations.AlterField(
            model_name='image',
            name='img_adress',
            field=models.ImageField(upload_to='images'),
        ),
    ]
